mqtt:
  hostname: 192.168.0.200
  port: 1883        # defaults to 1883
  user: ewaldharmsen
  password: 3e9mKWoP10ZRw05jfugK
#tls:
 # ca_certs:         # path/file preferrable use directory tls-files
 # certfile:         # path/file preferrable use directory tls-files
 # keyfile:          # path/file preferrable use directory tls-files
deviceName: rpi3
client_id: rpi3
ha_status: hass     # status topic for homeassistant: defaults to hass if key is omitted
timezone: Europe/Brussels
update_interval: 60 # Defaults to 60
sensors:
  temperature: true
  display: true
  slideshow: true
  slideshow2: true
  clock_speed: true
  fan_speed: false
  disk_use: true
  memory_use: true
  cpu_usage: true
  load_1m: true
  load_5m: true
  load_15m: true
  net_tx: false # true for all interfaces, otherwise the name of the interface
  net_rx: false # true for all interfaces, otherwise the name of the interface
  swap_usage: true
  power_status: true
  last_boot: true
  hostname: true
  host_ip: true
  host_os: true
  host_arch: true
  last_message: true
  updates: true
  wifi_strength: true
  wifi_ssid: true
  external_drives:
    # Only add mounted drives here, e.g.:
    # Drive1: /media/storage
    # For ZFS Pools use the format:
    # pool-name: /mount-point
